"""
K1 SoC SKiDL Symbol Definition
Auto-generated from soc_k1_pins.csv

Usage:
    from k1_soc_symbol import K1_SoC
    
    # Create an instance
    k1 = K1_SoC()
    
    # Access pins by name
    k1['GPIO_00'] += net_gpio_00
    k1['VCC_M1'] += vcc_0v9
"""

from skidl import Pin, Part, SKIDL, TEMPLATE

def K1_SoC():
    """
    K1 SoC Component Definition
    676-pin BGA package
    
    Functional Groups:
    - DDR/LPDDR Interface: LPDDR4X/LPDDR3 memory interface
    - GPIO: General Purpose I/O (GPIO_00 to GPIO_127)
    - JTAG: Debug interface
    - HDMI: Video output
    - MIPI CSI: Camera serial interface
    - MIPI DSI: Display serial interface
    - PCIe: PCI Express interfaces (A, B, C)
    - USB: USB 2.0 interfaces
    - SD/eMMC: Storage interfaces
    - QSPI: Quad SPI flash interface
    - Clock/Reference: Crystal oscillator and reference signals
    - Power Management: PMIC interface, reset, sleep control
    - Audio: Audio codec interface
    - Power/Ground: Power supply and ground pins
    """
    
    k1_soc = Part(
        'K1_SoC',
        'K1_SoC',
        dest=TEMPLATE,
        footprint='BGA-676'
    )
    
    # DDR/LPDDR Memory Interface
    Pin(name='VSSQ_DDR', num='A10', func=Pin.types.PWRIN)
    Pin(name='DQ_B_9', num='A11', func=Pin.types.PASSIVE)
    Pin(name='DQ_B_12', num='A12', func=Pin.types.PASSIVE)
    Pin(name='DQ_B_11', num='A13', func=Pin.types.PASSIVE)
    Pin(name='DQS1_C_B', num='A14', func=Pin.types.PASSIVE)
    Pin(name='DQS1_C_A', num='A15', func=Pin.types.PASSIVE)
    Pin(name='DQ_A_12', num='A16', func=Pin.types.PASSIVE)
    Pin(name='DQ_A_9', num='A17', func=Pin.types.PASSIVE)
    Pin(name='DQ_A_8', num='A18', func=Pin.types.PASSIVE)
    Pin(name='DQ_A_15', num='A19', func=Pin.types.PASSIVE)
    Pin(name='VSSQ_DDR', num='A2', func=Pin.types.PWRIN)
    Pin(name='VSSQ_DDR', num='A20', func=Pin.types.PWRIN)
    Pin(name='DQ_A_5', num='A21', func=Pin.types.PASSIVE)
    Pin(name='DQ_A_7', num='A22', func=Pin.types.PASSIVE)
    Pin(name='DMI0_A', num='A23', func=Pin.types.PASSIVE)
    Pin(name='DQ_A_1', num='A24', func=Pin.types.PASSIVE)
    Pin(name='VSSQ_DDR', num='A25', func=Pin.types.PWRIN)
    Pin(name='DQ_B_2', num='A3', func=Pin.types.PASSIVE)
    Pin(name='DMI0_B', num='A4', func=Pin.types.PASSIVE)
    Pin(name='VSSQ_DDR', num='A5', func=Pin.types.PWRIN)
    Pin(name='DQ_B_6', num='A6', func=Pin.types.PASSIVE)
    Pin(name='DQ_B_4', num='A7', func=Pin.types.PASSIVE)
    Pin(name='DQ_B_13', num='A8', func=Pin.types.PASSIVE)
    Pin(name='DQ_B_15', num='A9', func=Pin.types.PASSIVE)
    Pin(name='AVDD18_HDMI', num='AA10', func=Pin.types.PWRIN)
    Pin(name='AVSS_HDMI', num='AA7', func=Pin.types.PWRIN)
    Pin(name='HDMI_TX2N', num='AA8', func=Pin.types.OUTPUT)
    Pin(name='AVDD18_HDMI', num='AA9', func=Pin.types.PWRIN)
    Pin(name='HDMI_TXCN', num='AB4', func=Pin.types.OUTPUT)
    Pin(name='HDMI_TX0N', num='AB5', func=Pin.types.OUTPUT)
    Pin(name='AVSS_HDMI', num='AB6', func=Pin.types.PWRIN)
    Pin(name='HDMI_TX1N', num='AB7', func=Pin.types.OUTPUT)
    Pin(name='HDMI_TX2P', num='AB8', func=Pin.types.OUTPUT)
    Pin(name='AVSS_HDMI', num='AB9', func=Pin.types.PWRIN)
    Pin(name='HDMI_TXCP', num='AC4', func=Pin.types.OUTPUT)
    Pin(name='HDMI_TX0P', num='AC5', func=Pin.types.OUTPUT)
    Pin(name='AVSS_HDMI', num='AC6', func=Pin.types.PWRIN)
    Pin(name='HDMI_TX1P', num='AC7', func=Pin.types.OUTPUT)
    Pin(name='AVSS_HDMI', num='AC8', func=Pin.types.PWRIN)
    Pin(name='AVSS_HDMI', num='AC9', func=Pin.types.PWRIN)
    Pin(name='DMI1_B', num='B10', func=Pin.types.PASSIVE)
    Pin(name='DQ_B_8', num='B11', func=Pin.types.PASSIVE)
    Pin(name='DQ_B_10', num='B12', func=Pin.types.PASSIVE)
    Pin(name='VSSQ_DDR', num='B13', func=Pin.types.PWRIN)
    Pin(name='DQS1_T_B', num='B14', func=Pin.types.PASSIVE)
    Pin(name='DQS1_T_A', num='B15', func=Pin.types.PASSIVE)
    Pin(name='DQ_A_11', num='B16', func=Pin.types.PASSIVE)
    Pin(name='DQ_A_10', num='B17', func=Pin.types.PASSIVE)
    Pin(name='DMI1_A', num='B18', func=Pin.types.PASSIVE)
    Pin(name='DQ_A_14', num='B19', func=Pin.types.PASSIVE)
    Pin(name='DQ_B_3', num='B2', func=Pin.types.PASSIVE)
    Pin(name='DQ_A_13', num='B20', func=Pin.types.PASSIVE)
    Pin(name='DQ_A_4', num='B21', func=Pin.types.PASSIVE)
    Pin(name='DQ_A_6', num='B22', func=Pin.types.PASSIVE)
    Pin(name='VSSQ_DDR', num='B23', func=Pin.types.PWRIN)
    Pin(name='DQ_A_2', num='B24', func=Pin.types.PASSIVE)
    Pin(name='DQ_A_3', num='B25', func=Pin.types.PASSIVE)
    Pin(name='VSSQ_DDR', num='B3', func=Pin.types.PWRIN)
    Pin(name='DQ_B_1', num='B4', func=Pin.types.PASSIVE)
    Pin(name='DQ_B_0', num='B5', func=Pin.types.PASSIVE)
    Pin(name='DQ_B_7', num='B6', func=Pin.types.PASSIVE)
    Pin(name='DQ_B_5', num='B7', func=Pin.types.PASSIVE)
    Pin(name='VDDQ_V1P2', num='B8', func=Pin.types.PWRIN)
    Pin(name='DQ_B_14', num='B9', func=Pin.types.PASSIVE)
    Pin(name='CKE0_B', num='C10', func=Pin.types.OUTPUT)
    Pin(name='CKE1_B', num='C11', func=Pin.types.OUTPUT)
    Pin(name='VDDQ_V1P2', num='C12', func=Pin.types.PWRIN)
    Pin(name='CA_B_5', num='C13', func=Pin.types.OUTPUT)
    Pin(name='VSSQ_DDR', num='C14', func=Pin.types.PWRIN)
    Pin(name='VSSQ_DDR', num='C15', func=Pin.types.PWRIN)
    Pin(name='CA_A_4', num='C16', func=Pin.types.OUTPUT)
    Pin(name='VSSQ_DDR', num='C17', func=Pin.types.PWRIN)
    Pin(name='CKE1_A', num='C18', func=Pin.types.OUTPUT)
    Pin(name='CA_A_1', num='C19', func=Pin.types.OUTPUT)
    Pin(name='CS1_A', num='C20', func=Pin.types.OUTPUT)
    Pin(name='AVDD06_DDR', num='C21', func=Pin.types.PWRIN)
    Pin(name='DQ_A_0', num='C22', func=Pin.types.PASSIVE)
    Pin(name='DQS0_T_B', num='C6', func=Pin.types.PASSIVE)
    Pin(name='VSSQ_DDR', num='C7', func=Pin.types.PWRIN)
    Pin(name='CS1_B', num='C8', func=Pin.types.OUTPUT)
    Pin(name='CA_B_1', num='C9', func=Pin.types.OUTPUT)
    Pin(name='DDR_lp4x_SEL', num='D10', func=Pin.types.PASSIVE)
    Pin(name='CK_C_B', num='D11', func=Pin.types.OUTPUT)
    Pin(name='CA_B_2', num='D12', func=Pin.types.OUTPUT)
    Pin(name='CA_B_4', num='D13', func=Pin.types.OUTPUT)
    Pin(name='VSSQ_DDR', num='D14', func=Pin.types.PWRIN)
    Pin(name='AVDD06_DDR', num='D15', func=Pin.types.PWRIN)
    Pin(name='CA_A_2', num='D16', func=Pin.types.OUTPUT)
    Pin(name='CK_C_A', num='D17', func=Pin.types.OUTPUT)
    Pin(name='CKE0_A', num='D18', func=Pin.types.OUTPUT)
    Pin(name='CA_A_0', num='D19', func=Pin.types.OUTPUT)
    Pin(name='DQS0_T_A', num='D20', func=Pin.types.PASSIVE)
    Pin(name='DQS0_C_A', num='D21', func=Pin.types.PASSIVE)
    Pin(name='DQS0_C_B', num='D6', func=Pin.types.PASSIVE)
    Pin(name='VSSQ_DDR', num='D7', func=Pin.types.PWRIN)
    Pin(name='CA_B_0', num='D8', func=Pin.types.OUTPUT)
    Pin(name='VSSQ_DDR', num='D9', func=Pin.types.PWRIN)
    Pin(name='VSSQ_DDR', num='E10', func=Pin.types.PWRIN)
    Pin(name='CK_T_B', num='E11', func=Pin.types.OUTPUT)
    Pin(name='CA_B_3', num='E12', func=Pin.types.OUTPUT)
    Pin(name='AVSS18_DDR', num='E13', func=Pin.types.PWRIN)
    Pin(name='AVDD18_DDR', num='E14', func=Pin.types.PWRIN)
    Pin(name='CA_A_5', num='E15', func=Pin.types.OUTPUT)
    Pin(name='CS0_A', num='E16', func=Pin.types.OUTPUT)
    Pin(name='CK_T_A', num='E17', func=Pin.types.OUTPUT)
    Pin(name='AVDD06_DDR', num='E18', func=Pin.types.PWRIN)
    Pin(name='AVDD06_DDR', num='E19', func=Pin.types.PWRIN)
    Pin(name='VSSQ_DDR', num='E20', func=Pin.types.PWRIN)
    Pin(name='VSSQ_DDR', num='E7', func=Pin.types.PWRIN)
    Pin(name='VDDQ_V1P2', num='E8', func=Pin.types.PWRIN)
    Pin(name='DDR_LP23_VREFDQ', num='E9', func=Pin.types.PWRIN)
    Pin(name='VDDQ_V1P2', num='F10', func=Pin.types.PWRIN)
    Pin(name='VSSQ_DDR', num='F11', func=Pin.types.PWRIN)
    Pin(name='CS0_B', num='F12', func=Pin.types.OUTPUT)
    Pin(name='DDR_RESET_N', num='F13', func=Pin.types.OUTPUT)
    Pin(name='ZQ_DDR_PHY', num='F14', func=Pin.types.PASSIVE)
    Pin(name='CA_A_3', num='F15', func=Pin.types.OUTPUT)
    Pin(name='VSSQ_DDR', num='F16', func=Pin.types.PWRIN)
    Pin(name='DDR_LDO_CAP', num='F17', func=Pin.types.PASSIVE)
    Pin(name='AVDD06_DDR', num='F18', func=Pin.types.PWRIN)
    Pin(name='VSSQ_DDR', num='F19', func=Pin.types.PWRIN)
    Pin(name='VSSQ_DDR', num='F8', func=Pin.types.PWRIN)
    Pin(name='VDDQ_V1P2', num='F9', func=Pin.types.PWRIN)
    Pin(name='VSSQ_DDR', num='G10', func=Pin.types.PWRIN)
    Pin(name='VDDQ_V1P2', num='G11', func=Pin.types.PWRIN)
    Pin(name='AVDD11_DDR', num='G12', func=Pin.types.PWRIN)
    Pin(name='VDDQ_V1P2', num='G13', func=Pin.types.PWRIN)
    Pin(name='DDR_LP23_VREFCA', num='G14', func=Pin.types.PWRIN)
    Pin(name='AVDD11_DDR', num='G15', func=Pin.types.PWRIN)
    Pin(name='AVDD06_DDR', num='G16', func=Pin.types.PWRIN)
    Pin(name='VSSQ_DDR', num='G17', func=Pin.types.PWRIN)
    Pin(name='VSSU_DDR', num='H10', func=Pin.types.PWRIN)
    Pin(name='VSSU_DDR', num='H11', func=Pin.types.PWRIN)
    Pin(name='AVDDU_DDR', num='H13', func=Pin.types.PWRIN)
    Pin(name='AVSSU_DDR', num='H14', func=Pin.types.PWRIN)
    Pin(name='VSSU_DDR', num='H16', func=Pin.types.PWRIN)
    Pin(name='VSSU_DDR', num='H17', func=Pin.types.PWRIN)
    Pin(name='AVDD09_HDMI', num='Y10', func=Pin.types.PWRIN)
    Pin(name='AVDD33_HDMI', num='Y7', func=Pin.types.PWRIN)
    Pin(name='AVDD33_HDMI', num='Y8', func=Pin.types.PWRIN)
    Pin(name='AVDD09_HDMI', num='Y9', func=Pin.types.PWRIN)

    # General Purpose I/O
    Pin(name='GPIO_32', num='AA19', func=Pin.types.BIDIR)
    Pin(name='GPIO_29', num='AA20', func=Pin.types.BIDIR)
    Pin(name='GPIO_21', num='AA22', func=Pin.types.BIDIR)
    Pin(name='GPIO_24', num='AA23', func=Pin.types.BIDIR)
    Pin(name='GPIO_23', num='AA24', func=Pin.types.BIDIR)
    Pin(name='GPIO_25', num='AA25', func=Pin.types.BIDIR)
    Pin(name='GPIO_51', num='AB13', func=Pin.types.BIDIR)
    Pin(name='GPIO_78', num='AB15', func=Pin.types.BIDIR)
    Pin(name='GPIO_77', num='AB16', func=Pin.types.BIDIR)
    Pin(name='GPIO_02', num='AB17', func=Pin.types.BIDIR)
    Pin(name='GPIO_03', num='AB18', func=Pin.types.BIDIR)
    Pin(name='GPIO_41', num='AB21', func=Pin.types.BIDIR)
    Pin(name='GPIO_44', num='AB22', func=Pin.types.BIDIR)
    Pin(name='GPIO_19', num='AB23', func=Pin.types.BIDIR)
    Pin(name='GPIO_20', num='AB25', func=Pin.types.BIDIR)
    Pin(name='GPIO_22', num='AB26', func=Pin.types.BIDIR)
    Pin(name='GPIO_61', num='AC1', func=Pin.types.BIDIR)
    Pin(name='GPIO_86', num='AC10', func=Pin.types.BIDIR)
    Pin(name='GPIO_52', num='AC12', func=Pin.types.BIDIR)
    Pin(name='GPIO_47', num='AC13', func=Pin.types.BIDIR)
    Pin(name='GPIO_79', num='AC15', func=Pin.types.BIDIR)
    Pin(name='GPIO_05', num='AC17', func=Pin.types.BIDIR)
    Pin(name='GPIO_00', num='AC18', func=Pin.types.BIDIR)
    Pin(name='GPIO_62', num='AC2', func=Pin.types.BIDIR)
    Pin(name='GPIO_31', num='AC20', func=Pin.types.BIDIR)
    Pin(name='GPIO_34', num='AC21', func=Pin.types.BIDIR)
    Pin(name='GPIO_42', num='AC22', func=Pin.types.BIDIR)
    Pin(name='GPIO_43', num='AC23', func=Pin.types.BIDIR)
    Pin(name='GPIO_17', num='AC24', func=Pin.types.BIDIR)
    Pin(name='GPIO_18', num='AC26', func=Pin.types.BIDIR)
    Pin(name='GPIO_59', num='AD1', func=Pin.types.BIDIR)
    Pin(name='GPIO_50', num='AD12', func=Pin.types.BIDIR)
    Pin(name='GPIO_48', num='AD13', func=Pin.types.BIDIR)
    Pin(name='GPIO_76', num='AD15', func=Pin.types.BIDIR)
    Pin(name='GPIO_04', num='AD17', func=Pin.types.BIDIR)
    Pin(name='GPIO_01', num='AD18', func=Pin.types.BIDIR)
    Pin(name='GPIO_30', num='AD19', func=Pin.types.BIDIR)
    Pin(name='GPIO_60', num='AD2', func=Pin.types.BIDIR)
    Pin(name='GPIO_33', num='AD20', func=Pin.types.BIDIR)
    Pin(name='GPIO_14', num='AD23', func=Pin.types.BIDIR)
    Pin(name='GPIO_12', num='AD24', func=Pin.types.BIDIR)
    Pin(name='GPIO_16', num='AD25', func=Pin.types.BIDIR)
    Pin(name='GPIO_15', num='AD26', func=Pin.types.BIDIR)
    Pin(name='GPIO_87', num='AD8', func=Pin.types.BIDIR)
    Pin(name='GPIO_85', num='AD9', func=Pin.types.BIDIR)
    Pin(name='GPIO_75', num='AE16', func=Pin.types.BIDIR)
    Pin(name='GPIO_11', num='AE17', func=Pin.types.BIDIR)
    Pin(name='GPIO_07', num='AE18', func=Pin.types.BIDIR)
    Pin(name='GPIO_10', num='AE19', func=Pin.types.BIDIR)
    Pin(name='GPIO_37', num='AE20', func=Pin.types.BIDIR)
    Pin(name='GPIO_35', num='AE21', func=Pin.types.BIDIR)
    Pin(name='GPIO_38', num='AE22', func=Pin.types.BIDIR)
    Pin(name='GPIO_46', num='AE23', func=Pin.types.BIDIR)
    Pin(name='GPIO_13', num='AE25', func=Pin.types.BIDIR)
    Pin(name='GPIO_92', num='AE4', func=Pin.types.BIDIR)
    Pin(name='GPIO_90', num='AE5', func=Pin.types.BIDIR)
    Pin(name='GPIO_91', num='AE6', func=Pin.types.BIDIR)
    Pin(name='GPIO_89', num='AE7', func=Pin.types.BIDIR)
    Pin(name='GPIO_84', num='AE8', func=Pin.types.BIDIR)
    Pin(name='GPIO_81', num='AE9', func=Pin.types.BIDIR)
    Pin(name='GPIO_49', num='AF13', func=Pin.types.BIDIR)
    Pin(name='GPIO_80', num='AF16', func=Pin.types.BIDIR)
    Pin(name='GPIO_08', num='AF17', func=Pin.types.BIDIR)
    Pin(name='GPIO_06', num='AF18', func=Pin.types.BIDIR)
    Pin(name='GPIO_09', num='AF19', func=Pin.types.BIDIR)
    Pin(name='GPIO_40', num='AF21', func=Pin.types.BIDIR)
    Pin(name='GPIO_36', num='AF22', func=Pin.types.BIDIR)
    Pin(name='GPIO_39', num='AF23', func=Pin.types.BIDIR)
    Pin(name='GPIO_45', num='AF24', func=Pin.types.BIDIR)
    Pin(name='GPIO_88', num='AF6', func=Pin.types.BIDIR)
    Pin(name='GPIO_82', num='AF7', func=Pin.types.BIDIR)
    Pin(name='GPIO_83', num='AF8', func=Pin.types.BIDIR)
    Pin(name='GPIO_58', num='C1', func=Pin.types.BIDIR)
    Pin(name='GPIO_57', num='C2', func=Pin.types.BIDIR)
    Pin(name='GPIO_56', num='C3', func=Pin.types.BIDIR)
    Pin(name='GPIO_55', num='C4', func=Pin.types.BIDIR)
    Pin(name='GPIO_54', num='C5', func=Pin.types.BIDIR)
    Pin(name='GPIO_114', num='D1', func=Pin.types.BIDIR)
    Pin(name='GPIO_113', num='D2', func=Pin.types.BIDIR)
    Pin(name='GPIO_112', num='D3', func=Pin.types.BIDIR)
    Pin(name='GPIO_111', num='D4', func=Pin.types.BIDIR)
    Pin(name='GPIO_53', num='D5', func=Pin.types.BIDIR)
    Pin(name='GPIO_67', num='E1', func=Pin.types.BIDIR)
    Pin(name='GPIO_65', num='E2', func=Pin.types.BIDIR)
    Pin(name='GPIO_64', num='E3', func=Pin.types.BIDIR)
    Pin(name='GPIO_63', num='E5', func=Pin.types.BIDIR)
    Pin(name='GPIO_69', num='F3', func=Pin.types.BIDIR)
    Pin(name='GPIO_68', num='F4', func=Pin.types.BIDIR)
    Pin(name='GPIO_66', num='F5', func=Pin.types.BIDIR)
    Pin(name='GPIO_123', num='U21', func=Pin.types.BIDIR)
    Pin(name='GPIO_125', num='U22', func=Pin.types.BIDIR)
    Pin(name='GPIO_126', num='U25', func=Pin.types.BIDIR)
    Pin(name='GPIO_127', num='U26', func=Pin.types.BIDIR)
    Pin(name='GPIO_121', num='V21', func=Pin.types.BIDIR)
    Pin(name='GPIO_124', num='V23', func=Pin.types.BIDIR)
    Pin(name='GPIO_120', num='V24', func=Pin.types.BIDIR)
    Pin(name='GPIO_122', num='V26', func=Pin.types.BIDIR)
    Pin(name='GPIO_110', num='W21', func=Pin.types.BIDIR)
    Pin(name='GPIO_117', num='W22', func=Pin.types.BIDIR)
    Pin(name='GPIO_116', num='W23', func=Pin.types.BIDIR)
    Pin(name='GPIO_119', num='W25', func=Pin.types.BIDIR)
    Pin(name='GPIO_118', num='W26', func=Pin.types.BIDIR)
    Pin(name='GPIO_74', num='Y2', func=Pin.types.BIDIR)
    Pin(name='GPIO_26', num='Y22', func=Pin.types.BIDIR)
    Pin(name='GPIO_27', num='Y23', func=Pin.types.BIDIR)
    Pin(name='GPIO_28', num='Y25', func=Pin.types.BIDIR)
    Pin(name='GPIO_115', num='Y26', func=Pin.types.BIDIR)

    # JTAG Debug Interface
    Pin(name='PRI_TCK', num='AA1', func=Pin.types.BIDIR)
    Pin(name='PRI_TDO', num='AA2', func=Pin.types.BIDIR)
    Pin(name='PRI_TDI', num='AB1', func=Pin.types.BIDIR)
    Pin(name='PRI_TMS', num='AB2', func=Pin.types.BIDIR)
    Pin(name='JTAG_SEL', num='AF4', func=Pin.types.BIDIR)
    Pin(name='PRI_TRST_N', num='Y1', func=Pin.types.BIDIR)

    # MIPI CSI Camera Interface
    Pin(name='MIPI_CSI1_D1N', num='G1', func=Pin.types.INPUT)
    Pin(name='MIPI_CSI1_D1P', num='G2', func=Pin.types.INPUT)
    Pin(name='MIPI_CSI1_D0N', num='G4', func=Pin.types.INPUT)
    Pin(name='MIPI_CSI1_D0P', num='G5', func=Pin.types.INPUT)
    Pin(name='MIPI_CSI1_D2N', num='H1', func=Pin.types.INPUT)
    Pin(name='MIPI_CSI1_D2P', num='H2', func=Pin.types.INPUT)
    Pin(name='MIPI_CSI1_CLKN', num='H4', func=Pin.types.OUTPUT)
    Pin(name='MIPI_CSI1_CLKP', num='H5', func=Pin.types.OUTPUT)
    Pin(name='MIPI_CSI3_D0N', num='J1', func=Pin.types.INPUT)
    Pin(name='MIPI_CSI3_D0P', num='J2', func=Pin.types.INPUT)
    Pin(name='AVSS_CSI', num='J3', func=Pin.types.PWRIN)
    Pin(name='MIPI_CSI1_D3N', num='J4', func=Pin.types.INPUT)
    Pin(name='MIPI_CSI1_D3P', num='J5', func=Pin.types.INPUT)
    Pin(name='AVSS_CSI', num='J6', func=Pin.types.PWRIN)
    Pin(name='MIPI_CSI3_CLKN', num='K1', func=Pin.types.OUTPUT)
    Pin(name='MIPI_CSI3_CLKP', num='K2', func=Pin.types.OUTPUT)
    Pin(name='AVSS_CSI', num='K3', func=Pin.types.PWRIN)
    Pin(name='MIPI_CSI3_D1N', num='K4', func=Pin.types.INPUT)
    Pin(name='MIPI_CSI3_D1P', num='K5', func=Pin.types.INPUT)
    Pin(name='AVDD18_CSI', num='K6', func=Pin.types.PWRIN)
    Pin(name='AVDD09_CSI', num='K7', func=Pin.types.PWRIN)
    Pin(name='AVSS_CSI', num='K8', func=Pin.types.PWRIN)
    Pin(name='MIPI_CSI3_D2N', num='L1', func=Pin.types.INPUT)
    Pin(name='MIPI_CSI3_D2P', num='L2', func=Pin.types.INPUT)
    Pin(name='AVSS_CSI', num='L3', func=Pin.types.PWRIN)
    Pin(name='MIPI_CSI2_CLKN', num='L4', func=Pin.types.OUTPUT)
    Pin(name='MIPI_CSI2_CLKP', num='L5', func=Pin.types.OUTPUT)
    Pin(name='AVDD18_CSI', num='L6', func=Pin.types.PWRIN)
    Pin(name='AVDD09_CSI', num='L7', func=Pin.types.PWRIN)
    Pin(name='AVSS_CSI', num='L8', func=Pin.types.PWRIN)
    Pin(name='AVSS_CSI', num='L9', func=Pin.types.PWRIN)
    Pin(name='MIPI_CSI3_D3N', num='M1', func=Pin.types.INPUT)
    Pin(name='MIPI_CSI3_D3P', num='M2', func=Pin.types.INPUT)

    # MIPI DSI Display Interface
    Pin(name='AVDD18_DSI1', num='R6', func=Pin.types.PWRIN)
    Pin(name='MIPI_DSI1_D3N', num='T1', func=Pin.types.OUTPUT)
    Pin(name='MIPI_DSI1_D3P', num='T2', func=Pin.types.OUTPUT)
    Pin(name='AVDD09_DSI1', num='T7', func=Pin.types.PWRIN)
    Pin(name='AVDD12_DSI1', num='T8', func=Pin.types.PWRIN)
    Pin(name='MIPI_DSI1_D2N', num='U1', func=Pin.types.OUTPUT)
    Pin(name='MIPI_DSI1_D2P', num='U2', func=Pin.types.OUTPUT)
    Pin(name='AVSS_DSI1', num='U3', func=Pin.types.PWRIN)
    Pin(name='AVSS_DSI1', num='U4', func=Pin.types.PWRIN)
    Pin(name='AVSS_DSI1', num='U5', func=Pin.types.PWRIN)
    Pin(name='AVSS_DSI1', num='U7', func=Pin.types.PWRIN)
    Pin(name='MIPI_DSI1_CLKN', num='V1', func=Pin.types.OUTPUT)
    Pin(name='MIPI_DSI1_CLKP', num='V2', func=Pin.types.OUTPUT)
    Pin(name='AVSS_DSI1', num='V3', func=Pin.types.PWRIN)
    Pin(name='AVSS_DSI1', num='V4', func=Pin.types.PWRIN)
    Pin(name='AVSS_DSI1', num='V5', func=Pin.types.PWRIN)
    Pin(name='AVSS_DSI1', num='V6', func=Pin.types.PWRIN)
    Pin(name='MIPI_DSI1_D1N', num='W4', func=Pin.types.OUTPUT)
    Pin(name='MIPI_DSI1_D1P', num='W5', func=Pin.types.OUTPUT)
    Pin(name='MIPI_DSI1_D0N', num='Y4', func=Pin.types.OUTPUT)
    Pin(name='MIPI_DSI1_D0P', num='Y5', func=Pin.types.OUTPUT)

    # PCIe Interface A
    Pin(name='PCIEA_TXN', num='N4', func=Pin.types.OUTPUT)
    Pin(name='PCIEA_TXP', num='N5', func=Pin.types.OUTPUT)
    Pin(name='PCIEA_RXN', num='P1', func=Pin.types.INPUT)
    Pin(name='PCIEA_RXP', num='P2', func=Pin.types.INPUT)
    Pin(name='PCIEA_R_EXT', num='P4', func=Pin.types.OUTPUT)
    Pin(name='PCIEA_REFCLK_N', num='R1', func=Pin.types.PASSIVE)
    Pin(name='PCIEA_REFCLK_P', num='R2', func=Pin.types.PASSIVE)

    # PCIe Interface B
    Pin(name='PCIEB_RX0P', num='K25', func=Pin.types.INPUT)
    Pin(name='PCIEB_RX0N', num='K26', func=Pin.types.INPUT)
    Pin(name='PCIEB_TX0P', num='L22', func=Pin.types.OUTPUT)
    Pin(name='PCIEB_TX0N', num='L23', func=Pin.types.OUTPUT)
    Pin(name='PCIEB_REFCLK_P', num='L25', func=Pin.types.PASSIVE)
    Pin(name='PCIEB_REFCLK_N', num='L26', func=Pin.types.PASSIVE)
    Pin(name='PCIEB_TX1P', num='M22', func=Pin.types.OUTPUT)
    Pin(name='PCIEB_TX1N', num='M23', func=Pin.types.OUTPUT)
    Pin(name='PCIEB_RX1P', num='M25', func=Pin.types.INPUT)
    Pin(name='PCIEB_RX1N', num='M26', func=Pin.types.INPUT)

    # PCIe Interface C
    Pin(name='PCIEC_TX0P', num='H22', func=Pin.types.OUTPUT)
    Pin(name='PCIEC_TX0N', num='H23', func=Pin.types.OUTPUT)
    Pin(name='PCIEC_RX0P', num='H25', func=Pin.types.INPUT)
    Pin(name='PCIEC_RX0N', num='H26', func=Pin.types.INPUT)
    Pin(name='PCIEC_REFCLK_P', num='J22', func=Pin.types.PASSIVE)
    Pin(name='PCIEC_REFCLK_N', num='J23', func=Pin.types.PASSIVE)
    Pin(name='PCIEC_RX1P', num='J25', func=Pin.types.INPUT)
    Pin(name='PCIEC_RX1N', num='J26', func=Pin.types.INPUT)
    Pin(name='PCIEC_TX1P', num='K22', func=Pin.types.OUTPUT)
    Pin(name='PCIEC_TX1N', num='K23', func=Pin.types.OUTPUT)

    # USB 2.0 Interfaces
    Pin(name='AVDD18_USB', num='M6', func=Pin.types.PWRIN)
    Pin(name='AVDD09_USB', num='M7', func=Pin.types.PWRIN)
    Pin(name='AVDD33_USB', num='M9', func=Pin.types.PWRIN)
    Pin(name='USB2_DN', num='N1', func=Pin.types.PASSIVE)
    Pin(name='USB2_DP', num='N2', func=Pin.types.PASSIVE)
    Pin(name='AVSS_USB', num='N3', func=Pin.types.PWRIN)
    Pin(name='AVDD33_USB', num='N9', func=Pin.types.PWRIN)
    Pin(name='AVSS_USB', num='P3', func=Pin.types.PWRIN)
    Pin(name='AVSS_USB', num='P5', func=Pin.types.PWRIN)
    Pin(name='AVDD18_USB', num='P6', func=Pin.types.PWRIN)
    Pin(name='AVDD09_USB', num='P7', func=Pin.types.PWRIN)
    Pin(name='AVDD09_USB', num='P8', func=Pin.types.PWRIN)
    Pin(name='AVDD33_USB', num='P9', func=Pin.types.PWRIN)
    Pin(name='USB1_DN', num='R4', func=Pin.types.PASSIVE)
    Pin(name='USB1_DP', num='R5', func=Pin.types.PASSIVE)
    Pin(name='AVSS_USB', num='R7', func=Pin.types.PWRIN)
    Pin(name='USB0_DN', num='T4', func=Pin.types.PASSIVE)
    Pin(name='USB0_DP', num='T5', func=Pin.types.PASSIVE)

    # SD Card Interface (MMC1)
    Pin(name='VCC1833_MMC1', num='AA14', func=Pin.types.PWRIN)
    Pin(name='MMC1_DAT2', num='AA16', func=Pin.types.BIDIR)
    Pin(name='MMC1_DAT0', num='AB14', func=Pin.types.BIDIR)
    Pin(name='MMC1_CMD', num='AD14', func=Pin.types.BIDIR)
    Pin(name='MMC1_CLK', num='AE14', func=Pin.types.BIDIR)
    Pin(name='MMC1_DAT3', num='AE15', func=Pin.types.BIDIR)
    Pin(name='MMC1_DAT1', num='AF14', func=Pin.types.BIDIR)
    Pin(name='MMC1_VCC_CAP', num='Y14', func=Pin.types.PASSIVE)

    # eMMC Storage Interface
    Pin(name='EMMC_DS', num='C24', func=Pin.types.BIDIR)
    Pin(name='EMMC_D7', num='C25', func=Pin.types.BIDIR)
    Pin(name='EMMC_D2', num='C26', func=Pin.types.BIDIR)
    Pin(name='EMMC_D4', num='D23', func=Pin.types.BIDIR)
    Pin(name='EMMC_D1', num='D24', func=Pin.types.BIDIR)
    Pin(name='EMMC_D0', num='D26', func=Pin.types.BIDIR)
    Pin(name='AVSS_EMMC', num='E21', func=Pin.types.PWRIN)
    Pin(name='EMMC_D6', num='E22', func=Pin.types.BIDIR)
    Pin(name='AVSS_EMMC', num='E23', func=Pin.types.PWRIN)
    Pin(name='EMMC_CLK', num='E24', func=Pin.types.BIDIR)
    Pin(name='EMMC_D3', num='E25', func=Pin.types.BIDIR)
    Pin(name='EMMC_D5', num='E26', func=Pin.types.BIDIR)
    Pin(name='AVSS_EMMC', num='F20', func=Pin.types.PWRIN)
    Pin(name='AVSS_EMMC', num='F21', func=Pin.types.PWRIN)
    Pin(name='AVSS_EMMC', num='F22', func=Pin.types.PWRIN)
    Pin(name='EMMC_CMD', num='F25', func=Pin.types.BIDIR)
    Pin(name='AVSS_EMMC', num='G19', func=Pin.types.PWRIN)
    Pin(name='AVSS_EMMC', num='G20', func=Pin.types.PWRIN)
    Pin(name='AVSS_EMMC', num='G21', func=Pin.types.PWRIN)
    Pin(name='VSSU_EMMC', num='H18', func=Pin.types.PWRIN)
    Pin(name='AVDD18_EMMC', num='H19', func=Pin.types.PWRIN)
    Pin(name='AVDD09_EMMC', num='H20', func=Pin.types.PWRIN)
    Pin(name='VSSU_EMMC', num='J18', func=Pin.types.PWRIN)
    Pin(name='AVDD09_EMMC', num='J20', func=Pin.types.PWRIN)

    # QSPI Flash Interface
    Pin(name='QSPI_DAT2', num='F23', func=Pin.types.BIDIR)
    Pin(name='QSPI_DAT1', num='F24', func=Pin.types.BIDIR)
    Pin(name='QSPI_DAT0', num='F26', func=Pin.types.BIDIR)
    Pin(name='QSPI_DAT3', num='G22', func=Pin.types.BIDIR)
    Pin(name='QSPI_CLK', num='G23', func=Pin.types.BIDIR)
    Pin(name='QSPI_CS1', num='G24', func=Pin.types.BIDIR)
    Pin(name='VCC1833_QSPI', num='H21', func=Pin.types.PWRIN)
    Pin(name='QSPI_VCC_CAP', num='J19', func=Pin.types.PASSIVE)

    # Clock and Reference Signals
    Pin(name='EXT_32K_IN', num='AE12', func=Pin.types.BIDIR)
    Pin(name='MPLL_TST_AD', num='AE2', func=Pin.types.PASSIVE)
    Pin(name='XI_PAD', num='H7', func=Pin.types.INPUT)
    Pin(name='XO_PAD', num='J7', func=Pin.types.OUTPUT)
    Pin(name='BG_OUT', num='K11', func=Pin.types.OUTPUT)
    Pin(name='MPLL_TST_CK', num='K13', func=Pin.types.PASSIVE)

    # Power Management and Control
    Pin(name='PMIC_INT_N', num='AD10', func=Pin.types.BIDIR)
    Pin(name='DVL0', num='AE10', func=Pin.types.BIDIR)
    Pin(name='PWR_SCL', num='AE11', func=Pin.types.BIDIR)
    Pin(name='SLEEP_OUT', num='AF11', func=Pin.types.BIDIR)
    Pin(name='PWR_SDA', num='AF12', func=Pin.types.BIDIR)
    Pin(name='RESET_IN_N', num='AF3', func=Pin.types.BIDIR)
    Pin(name='DVL1', num='AF9', func=Pin.types.BIDIR)

    # Audio Interface
    Pin(name='AVSS18_AUD', num='N17', func=Pin.types.PWRIN)
    Pin(name='AVDD3V3_AUD', num='N18', func=Pin.types.PWRIN)
    Pin(name='AVSS18_AUD', num='N19', func=Pin.types.PWRIN)
    Pin(name='AVSS18_AUD', num='N20', func=Pin.types.PWRIN)
    Pin(name='AUD_GNDSNS', num='P17', func=Pin.types.PWRIN)
    Pin(name='AVDD18_AUD', num='P18', func=Pin.types.PWRIN)
    Pin(name='AVDD18_AUD', num='P19', func=Pin.types.PWRIN)
    Pin(name='AUD_VSSU', num='R17', func=Pin.types.PWRIN)
    Pin(name='AUD_VDDU09', num='R18', func=Pin.types.PWRIN)
    Pin(name='AUD_REFGND', num='R19', func=Pin.types.PWRIN)
    Pin(name='AUD_AUREF10', num='R21', func=Pin.types.PASSIVE)
    Pin(name='AVSS18_AUD', num='T21', func=Pin.types.PWRIN)
    Pin(name='AVSS18_AUD', num='T22', func=Pin.types.PWRIN)

    # Power Supply Pins
    Pin(name='VCC1833_GPIO3', num='AA13', func=Pin.types.PWRIN)
    Pin(name='VCC1833_GPIO2', num='AA15', func=Pin.types.PWRIN)
    Pin(name='VCC18_GPIO', num='AA21', func=Pin.types.PWRIN)
    Pin(name='VCC18_GPIO', num='AC11', func=Pin.types.PWRIN)
    Pin(name='VCC18_GPIO', num='AC14', func=Pin.types.PWRIN)
    Pin(name='VCC18_GPIO', num='AC3', func=Pin.types.PWRIN)
    Pin(name='VCC18_GPIO', num='AD11', func=Pin.types.PWRIN)
    Pin(name='VCC18_GPIO', num='AD21', func=Pin.types.PWRIN)
    Pin(name='VCC18_GPIO', num='AD22', func=Pin.types.PWRIN)
    Pin(name='VCC18_GPIO', num='F6', func=Pin.types.PWRIN)
    Pin(name='AVDD18_EFUSE', num='G18', func=Pin.types.PWRIN)
    Pin(name='AVDD18_PHY', num='H12', func=Pin.types.PWRIN)
    Pin(name='AVDD18_PHY', num='H15', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='J10', func=Pin.types.PWRIN)
    Pin(name='AVDDU_PHY', num='J11', func=Pin.types.PWRIN)
    Pin(name='AVDDU_PHY', num='J12', func=Pin.types.PWRIN)
    Pin(name='AVDDU_PHY', num='J13', func=Pin.types.PWRIN)
    Pin(name='AVDDU_PHY', num='J14', func=Pin.types.PWRIN)
    Pin(name='AVDDU_PHY', num='J15', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='J17', func=Pin.types.PWRIN)
    Pin(name='AVDD18_AFEAP', num='K12', func=Pin.types.PWRIN)
    Pin(name='AVDD18_PLL', num='K14', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='K15', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='K17', func=Pin.types.PWRIN)
    Pin(name='AVDD09_PCIEC', num='K20', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='K9', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='L10', func=Pin.types.PWRIN)
    Pin(name='AVDD09_AFEAP', num='L11', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='L16', func=Pin.types.PWRIN)
    Pin(name='AVDD18_PCIEC', num='L19', func=Pin.types.PWRIN)
    Pin(name='AVDD09_PCIEB', num='L20', func=Pin.types.PWRIN)
    Pin(name='AVDD09_PCIEB', num='L21', func=Pin.types.PWRIN)
    Pin(name='AVDD09_PLL', num='M11', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='M15', func=Pin.types.PWRIN)
    Pin(name='AVDD18_PCIEB', num='M19', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='N10', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='N12', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='N14', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='N16', func=Pin.types.PWRIN)
    Pin(name='AVDD18_PCIEA', num='N6', func=Pin.types.PWRIN)
    Pin(name='AVDD09_PCIEA', num='N7', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='P11', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='P13', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='P15', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='R10', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='R12', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='R14', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='R16', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='T11', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='T13', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='T15', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='T17', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='T9', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='U10', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='U12', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='U14', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='U16', func=Pin.types.PWRIN)
    Pin(name='VCC_M1_FB', num='U18', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='U6', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='U8', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='V11', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='V13', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='V15', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='V17', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='V7', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='V9', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='W10', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='W12', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='W14', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='W16', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='W18', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='W6', func=Pin.types.PWRIN)
    Pin(name='VCC_M1', num='W8', func=Pin.types.PWRIN)
    Pin(name='VCC18_GPIO', num='Y21', func=Pin.types.PWRIN)

    # Ground Pins
    Pin(name='VSS', num='A1', func=Pin.types.PWRIN)
    Pin(name='VSS', num='A26', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AA11', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AA12', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AA17', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AA18', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AA26', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AA3', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AA4', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AA5', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AA6', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AB10', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AB11', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AB12', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AB19', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AB20', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AB24', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AB3', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AC16', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AC19', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AC25', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AD16', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AD3', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AD4', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AD5', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AD6', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AD7', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AE1', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AE13', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AE24', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AE26', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AE3', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AF1', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AF10', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AF15', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AF2', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AF20', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AF25', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AF26', func=Pin.types.PWRIN)
    Pin(name='VSS', num='AF5', func=Pin.types.PWRIN)
    Pin(name='VSS', num='B1', func=Pin.types.PWRIN)
    Pin(name='VSS', num='B26', func=Pin.types.PWRIN)
    Pin(name='VSS', num='C23', func=Pin.types.PWRIN)
    Pin(name='VSS', num='D22', func=Pin.types.PWRIN)
    Pin(name='VSS', num='D25', func=Pin.types.PWRIN)
    Pin(name='VSS', num='E4', func=Pin.types.PWRIN)
    Pin(name='VSS', num='E6', func=Pin.types.PWRIN)
    Pin(name='VSS', num='F1', func=Pin.types.PWRIN)
    Pin(name='VSS', num='F2', func=Pin.types.PWRIN)
    Pin(name='VSS', num='F7', func=Pin.types.PWRIN)
    Pin(name='VSS', num='G25', func=Pin.types.PWRIN)
    Pin(name='VSS', num='G26', func=Pin.types.PWRIN)
    Pin(name='VSS', num='G3', func=Pin.types.PWRIN)
    Pin(name='VSS', num='G6', func=Pin.types.PWRIN)
    Pin(name='VSS', num='G7', func=Pin.types.PWRIN)
    Pin(name='VSS', num='G8', func=Pin.types.PWRIN)
    Pin(name='VSS', num='G9', func=Pin.types.PWRIN)
    Pin(name='AVSS_PCIEC', num='H24', func=Pin.types.PWRIN)
    Pin(name='VSS', num='H3', func=Pin.types.PWRIN)
    Pin(name='AVSS18_AFEAP', num='H6', func=Pin.types.PWRIN)
    Pin(name='AVSS18_AFEAP', num='H8', func=Pin.types.PWRIN)
    Pin(name='VSS', num='H9', func=Pin.types.PWRIN)
    Pin(name='VSS', num='J16', func=Pin.types.PWRIN)
    Pin(name='AVSS_PCIEC', num='J21', func=Pin.types.PWRIN)
    Pin(name='AVSS_PCIEC', num='J24', func=Pin.types.PWRIN)
    Pin(name='AVSS18_AFEAP', num='J8', func=Pin.types.PWRIN)
    Pin(name='AVSS18_AFEAP', num='J9', func=Pin.types.PWRIN)
    Pin(name='VSS', num='K10', func=Pin.types.PWRIN)
    Pin(name='VSS', num='K16', func=Pin.types.PWRIN)
    Pin(name='VSSU_PCIEC', num='K18', func=Pin.types.PWRIN)
    Pin(name='VSSU_PCIEC', num='K19', func=Pin.types.PWRIN)
    Pin(name='AVSS_PCIEC', num='K21', func=Pin.types.PWRIN)
    Pin(name='AVSS_PCIEC', num='K24', func=Pin.types.PWRIN)
    Pin(name='VSSU_AFEAP', num='L12', func=Pin.types.PWRIN)
    Pin(name='AVSS_PLL', num='L13', func=Pin.types.PWRIN)
    Pin(name='VSSU_PLL', num='L14', func=Pin.types.PWRIN)
    Pin(name='VSS', num='L15', func=Pin.types.PWRIN)
    Pin(name='VSSU_PCIEC', num='L17', func=Pin.types.PWRIN)
    Pin(name='VSSU_PCIEC', num='L18', func=Pin.types.PWRIN)
    Pin(name='AVSS_PCIEB', num='L24', func=Pin.types.PWRIN)
    Pin(name='VSS', num='M10', func=Pin.types.PWRIN)
    Pin(name='VSS', num='M12', func=Pin.types.PWRIN)
    Pin(name='VSS', num='M13', func=Pin.types.PWRIN)
    Pin(name='VSS', num='M14', func=Pin.types.PWRIN)
    Pin(name='VSS', num='M16', func=Pin.types.PWRIN)
    Pin(name='VSSU_PCIEB', num='M17', func=Pin.types.PWRIN)
    Pin(name='VSSU_PCIEB', num='M18', func=Pin.types.PWRIN)
    Pin(name='AVSS_PCIEB', num='M20', func=Pin.types.PWRIN)
    Pin(name='AVSS_PCIEB', num='M21', func=Pin.types.PWRIN)
    Pin(name='AVSS_PCIEB', num='M24', func=Pin.types.PWRIN)
    Pin(name='VSS', num='M3', func=Pin.types.PWRIN)
    Pin(name='VSS', num='M4', func=Pin.types.PWRIN)
    Pin(name='VSSU_PCIEA', num='M5', func=Pin.types.PWRIN)
    Pin(name='VSSU_PCIEA', num='M8', func=Pin.types.PWRIN)
    Pin(name='VSS', num='N11', func=Pin.types.PWRIN)
    Pin(name='VSS', num='N13', func=Pin.types.PWRIN)
    Pin(name='VSS', num='N15', func=Pin.types.PWRIN)
    Pin(name='AVSS_PCIEA', num='N8', func=Pin.types.PWRIN)
    Pin(name='VSS', num='P10', func=Pin.types.PWRIN)
    Pin(name='VSS', num='P12', func=Pin.types.PWRIN)
    Pin(name='VSS', num='P14', func=Pin.types.PWRIN)
    Pin(name='VSS', num='P16', func=Pin.types.PWRIN)
    Pin(name='VSS', num='R11', func=Pin.types.PWRIN)
    Pin(name='VSS', num='R13', func=Pin.types.PWRIN)
    Pin(name='VSS', num='R15', func=Pin.types.PWRIN)
    Pin(name='VSS', num='R24', func=Pin.types.PWRIN)
    Pin(name='VSS', num='R3', func=Pin.types.PWRIN)
    Pin(name='VSS', num='R8', func=Pin.types.PWRIN)
    Pin(name='VSS', num='R9', func=Pin.types.PWRIN)
    Pin(name='VSS', num='T10', func=Pin.types.PWRIN)
    Pin(name='VSS', num='T12', func=Pin.types.PWRIN)
    Pin(name='VSS', num='T14', func=Pin.types.PWRIN)
    Pin(name='VSS', num='T16', func=Pin.types.PWRIN)
    Pin(name='VSS', num='T18', func=Pin.types.PWRIN)
    Pin(name='VSS', num='T19', func=Pin.types.PWRIN)
    Pin(name='VSS', num='T20', func=Pin.types.PWRIN)
    Pin(name='VSS', num='T24', func=Pin.types.PWRIN)
    Pin(name='VSS', num='T26', func=Pin.types.PWRIN)
    Pin(name='VSS', num='T3', func=Pin.types.PWRIN)
    Pin(name='VSS', num='T6', func=Pin.types.PWRIN)
    Pin(name='VSS', num='U11', func=Pin.types.PWRIN)
    Pin(name='VSS', num='U13', func=Pin.types.PWRIN)
    Pin(name='VSS', num='U15', func=Pin.types.PWRIN)
    Pin(name='VSS', num='U17', func=Pin.types.PWRIN)
    Pin(name='VSS_FB', num='U19', func=Pin.types.PWRIN)
    Pin(name='VSS', num='U20', func=Pin.types.PWRIN)
    Pin(name='VSS', num='U9', func=Pin.types.PWRIN)
    Pin(name='VSS', num='V10', func=Pin.types.PWRIN)
    Pin(name='VSS', num='V12', func=Pin.types.PWRIN)
    Pin(name='VSS', num='V14', func=Pin.types.PWRIN)
    Pin(name='VSS', num='V16', func=Pin.types.PWRIN)
    Pin(name='VSS', num='V18', func=Pin.types.PWRIN)
    Pin(name='VSS', num='V19', func=Pin.types.PWRIN)
    Pin(name='VSS', num='V20', func=Pin.types.PWRIN)
    Pin(name='VSS', num='V22', func=Pin.types.PWRIN)
    Pin(name='VSS', num='V25', func=Pin.types.PWRIN)
    Pin(name='VSS', num='V8', func=Pin.types.PWRIN)
    Pin(name='VSS', num='W1', func=Pin.types.PWRIN)
    Pin(name='VSS', num='W11', func=Pin.types.PWRIN)
    Pin(name='VSS', num='W15', func=Pin.types.PWRIN)
    Pin(name='VSS', num='W17', func=Pin.types.PWRIN)
    Pin(name='VSS', num='W19', func=Pin.types.PWRIN)
    Pin(name='VSS', num='W2', func=Pin.types.PWRIN)
    Pin(name='VSS', num='W20', func=Pin.types.PWRIN)
    Pin(name='VSS', num='W24', func=Pin.types.PWRIN)
    Pin(name='VSS', num='W3', func=Pin.types.PWRIN)
    Pin(name='VSS', num='W7', func=Pin.types.PWRIN)
    Pin(name='VSS', num='W9', func=Pin.types.PWRIN)
    Pin(name='VSS', num='Y11', func=Pin.types.PWRIN)
    Pin(name='VSS', num='Y12', func=Pin.types.PWRIN)
    Pin(name='VSS', num='Y13', func=Pin.types.PWRIN)
    Pin(name='VSS', num='Y16', func=Pin.types.PWRIN)
    Pin(name='VSS', num='Y17', func=Pin.types.PWRIN)
    Pin(name='VSS', num='Y18', func=Pin.types.PWRIN)
    Pin(name='VSS', num='Y19', func=Pin.types.PWRIN)
    Pin(name='VSS', num='Y20', func=Pin.types.PWRIN)
    Pin(name='VSS', num='Y24', func=Pin.types.PWRIN)
    Pin(name='VSS', num='Y3', func=Pin.types.PWRIN)
    Pin(name='VSS', num='Y6', func=Pin.types.PWRIN)

    # Not Connected
    Pin(name='NC', num='N21', func=Pin.types.PWRIN)
    Pin(name='NC', num='N22', func=Pin.types.PWRIN)
    Pin(name='NC', num='N23', func=Pin.types.OUTPUT)
    Pin(name='NC', num='N24', func=Pin.types.OUTPUT)
    Pin(name='NC', num='N25', func=Pin.types.OUTPUT)
    Pin(name='NC', num='N26', func=Pin.types.OUTPUT)
    Pin(name='NC', num='P20', func=Pin.types.OUTPUT)
    Pin(name='NC', num='P21', func=Pin.types.OUTPUT)
    Pin(name='NC', num='P22', func=Pin.types.OUTPUT)
    Pin(name='NC', num='P23', func=Pin.types.INPUT)
    Pin(name='NC', num='P24', func=Pin.types.INPUT)
    Pin(name='NC', num='P25', func=Pin.types.INPUT)
    Pin(name='NC', num='P26', func=Pin.types.INPUT)
    Pin(name='NC', num='R20', func=Pin.types.OUTPUT)
    Pin(name='NC', num='R22', func=Pin.types.INPUT)
    Pin(name='NC', num='R23', func=Pin.types.INPUT)
    Pin(name='NC', num='R25', func=Pin.types.INPUT)
    Pin(name='NC', num='R26', func=Pin.types.INPUT)
    Pin(name='NC', num='T23', func=Pin.types.INPUT)
    Pin(name='NC', num='T25', func=Pin.types.OUTPUT)
    Pin(name='NC', num='U23', func=Pin.types.INPUT)
    Pin(name='NC', num='U24', func=Pin.types.OUTPUT)

    # Other Signals
    Pin(name='GPIO3_VCC_CAP', num='W13', func=Pin.types.PASSIVE)
    Pin(name='GPIO2_VCC_CAP', num='Y15', func=Pin.types.PASSIVE)

    return k1_soc


if __name__ == '__main__':
    # Example usage
    k1 = K1_SoC()
    print(f'K1 SoC component created with {len(k1)} pins')
